#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/5822385d-44a3-4676-84f6-f4a2970a81b9/ # 
title: test

/theme/ids/{themeid}:
  description: This of resource
  uriParameters: 
    themeid: 
      description: This is a description of uri param
      required: false
  get:
    description: Get Service.